### ISSUE TITLE
Application crashes after multiple changing of camera modals and minimizing app.

### ISSUE THREAD

**Issue by IrynaChernenko** [novaphotos/nova-ios-app#137]
iPhone 5
iOS 7.1.1

Reproducable rate: 40%

Steps to reproduce:
1. Install app on device.
2. Tap fast on the button to change the camera modal
3. Minimize application and open it again.

Actual result: Application crashes after multiple changing of camera modals and minimizing app.

Expected result: Application doesn't crash.

Crashlog: https://www.dropbox.com/s/sqbu1aq5sunuzfm/iphone5crashlog001.txt

**Comment by joewalnes** [comment]
Fixed in a44c3d5

**Comment by IrynaChernenko** [comment]
iPhone 5s, iOS 7.1.1
Fixed
