### ISSUE TITLE
Application freezes after saving edited photo in photo editor.

### ISSUE THREAD

**Issue by IrynaChernenko** [novaphotos/nova-ios-app#141]
iPhone 5S
iOs 7.0.6

Steps to reproduce:
1. Install and run app on device.
2. Go to image gallery.
3. Choose any image and start editing it.
4. Tap "Done" in photo editor screen.

Actual result: Application freezes after saving edited photo in photo editor.
Expected result: Application doesnt freez.

Video: https://www.dropbox.com/s/p8hgedotrq2h357/20140709_163140_001.3gp

**Comment by joewalnes** [comment]
@IrynaChernenko: Does this freeze forever, or does it eventually come back?

**Comment by joewalnes** [comment]
Fixed by 1ab4972

**Comment by IrynaChernenko** [comment]
iPhone 5s iOS 7.1.1
Fixed

**Comment by IrynaChernenko** [comment]
Randomly reproducing on iPhone 5S iOS 7.0.6.
