### ISSUE TITLE
Black color icon in photo editor screen doesn't have white borders which makes it impossible to see on black background.

### ISSUE THREAD

**Issue by IrynaChernenko** [novaphotos/nova-ios-app#142]
![img_1103](https://cloud.githubusercontent.com/assets/8088814/3906148/38ea7262-22f0-11e4-9eb3-041dabd5ee1a.PNG)
iPhone 5S
iOS 7.0.6

Steps to reproduce:
1. Install and run app on device.
2. Go to image gallery.
3. Choose any image and start editing it.
4. Choose "Draw" or "text"
5. Pay attention to black color icon at the bottom of editor screen.

Actual result: black color icon is impossible to see on black background. Icon doesn't have white border.

Expected result: black color icon is possible to see on black background.

![2032-249342](https://cloud.githubusercontent.com/assets/8088814/3525912/a9cec0a8-0777-11e4-9ad9-5226f731d8ac.png)

**Comment by joewalnes** [comment]
Fixed

**Comment by IrynaChernenko** [comment]
iPhone 5s iOS 7.1.1
Fixed

**Comment by IrynaChernenko** [comment]
Reproduced on iPhone 5S iOS 7.0.6
