### ISSUE TITLE
Flash settings icon should reflect current setting

### ISSUE THREAD

**Issue by joewalnes** [novaphotos/nova-ios-app#16]
The flash settings icon in the bottom right corner (the flower) should change based on what the current setting is.

**Comment by pix0r** [comment]
The icon is actually a status, not setting.  The states are:
- Default/empty (no icon; assume this is used when the flash is not connected)
- Searching
- OK
- Error

This will be populated based on the current `NVFlashServiceStatus` (see https://github.com/nova-device/nova-ios-sdk/blob/master/NovaSDK/NVFlashServiceStatus.h).

As a side note, I think KVO would be a better pattern than a single delegate for observing changes to the status in `NVFlashService` (https://github.com/nova-device/nova-ios-sdk/blob/master/NovaSDK/NVFlashService.h#L55).  There may be several parties interested in status changes and the `observeStatus:` callback mechanism only supports one.  (I'd simply deprecate the `observeStatus:` method; you're using a property for the `NVFlashServiceStatus` so KVO is already handled for you - it's just a matter of consuming the notifications.)

**Comment by pix0r** [comment]
Added new feature #27 to capture this functionality.

**Comment by joewalnes** [comment]
Yeah I was in two minds about that callback. I think I'll delete it and force KVO. Just a shame KVO has such a clunky API.
