### ISSUE TITLE
Album / photo picker does not rotate to landscape orientation

### ISSUE THREAD

**Issue by joewalnes** [novaphotos/nova-ios-app#21]

**Comment by pix0r** [comment]
Unfortunately this is documented in the [`UIImagePickerController` reference](https://developer.apple.com/library/ios/documentation/uikit/reference/UIImagePickerController_Class/UIImagePickerController/UIImagePickerController.html#//apple_ref/doc/uid/TP40007070-CH3-DontLinkElementID_1)

> Important: The `UIImagePickerController` class supports portrait mode only. This class is intended to be used as-is and does not support subclassing. The view hierarchy for this class is private and must not be modified, with one exception. You can assign a custom view to the `cameraOverlayView` property and use that view to present additional information or manage the interactions between the camera interface and your code.

**Comment by joewalnes** [comment]
Fair enough. Aviary also has this constraint.
