### ISSUE TITLE
Landscape photos are stored as portrait

### ISSUE THREAD

**Issue by joewalnes** [novaphotos/nova-ios-app#33]
Take a photo with the phone in landscape orientation. The resulting photo is a portrait photo and needs to be rotated 90degrees.

**Comment by pix0r** [comment]
I've pushed 04c829e which may fix this. I can't test at the moment because I need to set up Crashlytics locally in order to compile.

**Comment by joewalnes** [comment]
Sorta works. After rotation it saves correctly, but if the app is never rotated (hence deviceOrientationDidChange never fires) it saves with an incorrect orientation.
