### ISSUE TITLE
Does not ask to share after ask to edit

### ISSUE THREAD

**Issue by joewalnes** [novaphotos/nova-ios-app#34]
Steps to reproduce:
-   Open settings. Enable both "ask to edit..." and "ask to share..."
-   Return to camera screen and take a photo
-   After taking photo Aviary editor will open. Hit "done"

Expected result:
-   Sharing screen should appear

Actual result:
-   Returns to photo viewer

**Comment by pix0r** [comment]
Commit 7f4d1ea should address this but I'm not able to test at the moment.

**Comment by joewalnes** [comment]
Still not working.
