### ISSUE TITLE
0.1.0 release: Remove unfinished functionality

### ISSUE THREAD

**Issue by joewalnes** [novaphotos/nova-ios-app#37]
This is just for the 0.1.0 release. Remove any functionality from the UI that is not 100% complete. 

This is:
-   Settings: All menu items except for the "edit after" and "share after" items.
-   Custom flash settings: This is due to a certain flash settings interfering with the Bluetooth radio. Lock down to the presets until the allowed settings are known.
-   Mark build as iPhone only for AppStore (no universal / iPad support)

**Comment by pix0r** [comment]
Use multiple novas should actually work- there was just a mismatch in the settings key I was looking up.  Should be fixed in 1cfbf65.

**Comment by pix0r** [comment]
Removed settings for grid lines & square photos in 0211b56 (fixed).

**Comment by pix0r** [comment]
Disabled custom flash mode in both the flash service and the settings view (see e91e7b0)
