### ISSUE TITLE
Custom flash brightness settings

### ISSUE THREAD

**Issue by joewalnes** [novaphotos/nova-ios-app#80]
Resurrect the "custom" brightness settings (now this is confirmed fixed in the production PCBs).

However sliders should simply be: "Warm brightness" and "Cool brightness" which map directly to PWM values.

**Comment by pix0r** [comment]
This is ready to test; I'll send a pull request after you've pushed your latest develop branch and I have a chance to rebase.  (Don't work on this feature branch as it'll be changing when I rebase.)
