### ISSUE TITLE
Implement pinch to zoom

### ISSUE THREAD

**Issue by joewalnes** [novaphotos/nova-ios-app#9]

**Comment by pix0r** [comment]
4add20f adds basic pinch to zoom support, but lacks a UI, and forces the zoom to be reset after each picture is taken due to an as-of-yet unresolved glitch with the transform applied to the preview layer.

Should we add a UI similar to the native iOS camera app?

**Comment by joewalnes** [comment]
Yep

**Comment by pix0r** [comment]
Should I attempt to replicate that design or do you want to put something
together?

**Comment by joewalnes** [comment]
Replicate for now.
